# Publish a Python package to PyPi using uv
name: Publish Package on PyPi

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          # Pinned Python version
          python-version-file: ".python-version"
      - name: Build package
        run: uv build
      - name: Publish package
        run: uv publish -t ${{ secrets.PYPI_API_TOKEN }}
